---
- name: Start sonarqube with docker-compose
  docker_service:
    project_name: sonarqube
    definition:
      version: '3.3'

      services:
        sonarqube:
          restart: always
          links:
            - db
          depends_on:
            - db
          image: sonarqube:6.7-alpine
          ports:
            - 9000:9000
          networks:
            - sonarnet
          environment:
            - SONARQUBE_JDBC_URL={{ sonar_uri }}
            - SONARQUBE_JDBC_USERNAME={{ sonar_db_user }}
            - SONARQUBE_JDBC_PASSWORD={{ sonar_db_password }}
          volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

        db:
          image: postgres:10-alpine
          restart: always
          expose:
            - '5432'
          networks:
            - sonarnet
          environment:
            - POSTGRES_USER:{{ sonar_db_user }}
            - POSTGRES_PASSWORD:{{ sonar_db_password }}
          volumes:
            - postgresql:/var/lib/postgresql
            # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
            - postgresql_data:/var/lib/postgresql/data

      networks:
        sonarnet:
          driver: bridge

      volumes:
        sonarqube_conf:
        sonarqube_data:
        sonarqube_extensions:
        sonarqube_bundled-plugins:
        postgresql:
        postgresql_data:
  vars:
    ansible_python_interpreter: /tmp/.venv/bin/python
